services:
  server:
    image: archlinux:latest
    volumes:
      - ./build:/app/bin:ro
      - ./mockfiles/server:/app/mockfiles
    working_dir: /app
    command: ./bin/SquidStorageServer 12345 2 10
    ports:
      - "12345:12345"
    networks:
      squid_network:
        ipv4_address: 172.20.0.10

  datanode1:
    image: archlinux:latest
    volumes:
      - ./build:/app/bin:ro
      - ./mockfiles/datanode_alpha:/app/mockfiles
    working_dir: /app
    command: ./bin/DataNode 172.20.0.10 12345 DATANODE_ALPHA
    depends_on:
      - server
    networks:
      squid_network:
        ipv4_address: 172.20.0.11

  datanode2:
    image: archlinux:latest
    volumes:
      - ./build:/app/bin:ro
      - ./mockfiles/datanode_beta:/app/mockfiles
    working_dir: /app
    command: ./bin/DataNode 172.20.0.10 12345 DATANODE_BETA
    depends_on:
      - server
    networks:
      squid_network:
        ipv4_address: 172.20.0.12

  mock_client:
    image: archlinux:latest
    volumes:
      - ./build:/app/bin:ro
      - ./mockfiles/client:/app/mockfiles
    working_dir: /app
    command: ./bin/SquidStorageClient 172.20.0.10 12345 12346 MOCK_CLIENT_CONTAINER
    depends_on:
      - datanode1
      - datanode2
    networks:
      squid_network:
        ipv4_address: 172.20.0.20

networks:
  squid_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
