# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /sbin/cmake

# The command to remove a file.
RM = /sbin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/sentinel/Projects/Squid Storage"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/sentinel/Projects/Squid Storage"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/sbin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/sbin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/sentinel/Projects/Squid Storage/CMakeFiles" "/home/sentinel/Projects/Squid Storage//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/sentinel/Projects/Squid Storage/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SquidStorage

# Build rule for target.
SquidStorage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SquidStorage
.PHONY : SquidStorage

# fast build rule for target.
SquidStorage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/build
.PHONY : SquidStorage/fast

#=============================================================================
# Target rules for targets named SquidStorageServer

# Build rule for target.
SquidStorageServer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SquidStorageServer
.PHONY : SquidStorageServer

# fast build rule for target.
SquidStorageServer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorageServer.dir/build.make CMakeFiles/SquidStorageServer.dir/build
.PHONY : SquidStorageServer/fast

#=============================================================================
# Target rules for targets named DataNode

# Build rule for target.
DataNode: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DataNode
.PHONY : DataNode

# fast build rule for target.
DataNode/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DataNode.dir/build.make CMakeFiles/DataNode.dir/build
.PHONY : DataNode/fast

client/src/client.o: client/src/client.cpp.o
.PHONY : client/src/client.o

# target to build an object file
client/src/client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/client/src/client.cpp.o
.PHONY : client/src/client.cpp.o

client/src/client.i: client/src/client.cpp.i
.PHONY : client/src/client.i

# target to preprocess a source file
client/src/client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/client/src/client.cpp.i
.PHONY : client/src/client.cpp.i

client/src/client.s: client/src/client.cpp.s
.PHONY : client/src/client.s

# target to generate assembly for a file
client/src/client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/client/src/client.cpp.s
.PHONY : client/src/client.cpp.s

common/src/filesystem/filelock.o: common/src/filesystem/filelock.cpp.o
.PHONY : common/src/filesystem/filelock.o

# target to build an object file
common/src/filesystem/filelock.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/common/src/filesystem/filelock.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorageServer.dir/build.make CMakeFiles/SquidStorageServer.dir/common/src/filesystem/filelock.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DataNode.dir/build.make CMakeFiles/DataNode.dir/common/src/filesystem/filelock.cpp.o
.PHONY : common/src/filesystem/filelock.cpp.o

common/src/filesystem/filelock.i: common/src/filesystem/filelock.cpp.i
.PHONY : common/src/filesystem/filelock.i

# target to preprocess a source file
common/src/filesystem/filelock.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/common/src/filesystem/filelock.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorageServer.dir/build.make CMakeFiles/SquidStorageServer.dir/common/src/filesystem/filelock.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DataNode.dir/build.make CMakeFiles/DataNode.dir/common/src/filesystem/filelock.cpp.i
.PHONY : common/src/filesystem/filelock.cpp.i

common/src/filesystem/filelock.s: common/src/filesystem/filelock.cpp.s
.PHONY : common/src/filesystem/filelock.s

# target to generate assembly for a file
common/src/filesystem/filelock.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/common/src/filesystem/filelock.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorageServer.dir/build.make CMakeFiles/SquidStorageServer.dir/common/src/filesystem/filelock.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DataNode.dir/build.make CMakeFiles/DataNode.dir/common/src/filesystem/filelock.cpp.s
.PHONY : common/src/filesystem/filelock.cpp.s

common/src/filesystem/filemanager.o: common/src/filesystem/filemanager.cpp.o
.PHONY : common/src/filesystem/filemanager.o

# target to build an object file
common/src/filesystem/filemanager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/common/src/filesystem/filemanager.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorageServer.dir/build.make CMakeFiles/SquidStorageServer.dir/common/src/filesystem/filemanager.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DataNode.dir/build.make CMakeFiles/DataNode.dir/common/src/filesystem/filemanager.cpp.o
.PHONY : common/src/filesystem/filemanager.cpp.o

common/src/filesystem/filemanager.i: common/src/filesystem/filemanager.cpp.i
.PHONY : common/src/filesystem/filemanager.i

# target to preprocess a source file
common/src/filesystem/filemanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/common/src/filesystem/filemanager.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorageServer.dir/build.make CMakeFiles/SquidStorageServer.dir/common/src/filesystem/filemanager.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DataNode.dir/build.make CMakeFiles/DataNode.dir/common/src/filesystem/filemanager.cpp.i
.PHONY : common/src/filesystem/filemanager.cpp.i

common/src/filesystem/filemanager.s: common/src/filesystem/filemanager.cpp.s
.PHONY : common/src/filesystem/filemanager.s

# target to generate assembly for a file
common/src/filesystem/filemanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/common/src/filesystem/filemanager.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorageServer.dir/build.make CMakeFiles/SquidStorageServer.dir/common/src/filesystem/filemanager.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DataNode.dir/build.make CMakeFiles/DataNode.dir/common/src/filesystem/filemanager.cpp.s
.PHONY : common/src/filesystem/filemanager.cpp.s

common/src/filesystem/filetransfer.o: common/src/filesystem/filetransfer.cpp.o
.PHONY : common/src/filesystem/filetransfer.o

# target to build an object file
common/src/filesystem/filetransfer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/common/src/filesystem/filetransfer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorageServer.dir/build.make CMakeFiles/SquidStorageServer.dir/common/src/filesystem/filetransfer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DataNode.dir/build.make CMakeFiles/DataNode.dir/common/src/filesystem/filetransfer.cpp.o
.PHONY : common/src/filesystem/filetransfer.cpp.o

common/src/filesystem/filetransfer.i: common/src/filesystem/filetransfer.cpp.i
.PHONY : common/src/filesystem/filetransfer.i

# target to preprocess a source file
common/src/filesystem/filetransfer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/common/src/filesystem/filetransfer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorageServer.dir/build.make CMakeFiles/SquidStorageServer.dir/common/src/filesystem/filetransfer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DataNode.dir/build.make CMakeFiles/DataNode.dir/common/src/filesystem/filetransfer.cpp.i
.PHONY : common/src/filesystem/filetransfer.cpp.i

common/src/filesystem/filetransfer.s: common/src/filesystem/filetransfer.cpp.s
.PHONY : common/src/filesystem/filetransfer.s

# target to generate assembly for a file
common/src/filesystem/filetransfer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/common/src/filesystem/filetransfer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorageServer.dir/build.make CMakeFiles/SquidStorageServer.dir/common/src/filesystem/filetransfer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DataNode.dir/build.make CMakeFiles/DataNode.dir/common/src/filesystem/filetransfer.cpp.s
.PHONY : common/src/filesystem/filetransfer.cpp.s

common/src/peer/peer.o: common/src/peer/peer.cpp.o
.PHONY : common/src/peer/peer.o

# target to build an object file
common/src/peer/peer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/common/src/peer/peer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorageServer.dir/build.make CMakeFiles/SquidStorageServer.dir/common/src/peer/peer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DataNode.dir/build.make CMakeFiles/DataNode.dir/common/src/peer/peer.cpp.o
.PHONY : common/src/peer/peer.cpp.o

common/src/peer/peer.i: common/src/peer/peer.cpp.i
.PHONY : common/src/peer/peer.i

# target to preprocess a source file
common/src/peer/peer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/common/src/peer/peer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorageServer.dir/build.make CMakeFiles/SquidStorageServer.dir/common/src/peer/peer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DataNode.dir/build.make CMakeFiles/DataNode.dir/common/src/peer/peer.cpp.i
.PHONY : common/src/peer/peer.cpp.i

common/src/peer/peer.s: common/src/peer/peer.cpp.s
.PHONY : common/src/peer/peer.s

# target to generate assembly for a file
common/src/peer/peer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/common/src/peer/peer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorageServer.dir/build.make CMakeFiles/SquidStorageServer.dir/common/src/peer/peer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DataNode.dir/build.make CMakeFiles/DataNode.dir/common/src/peer/peer.cpp.s
.PHONY : common/src/peer/peer.cpp.s

common/src/squidprotocol/squidProtocolFormatter.o: common/src/squidprotocol/squidProtocolFormatter.cpp.o
.PHONY : common/src/squidprotocol/squidProtocolFormatter.o

# target to build an object file
common/src/squidprotocol/squidProtocolFormatter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/common/src/squidprotocol/squidProtocolFormatter.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorageServer.dir/build.make CMakeFiles/SquidStorageServer.dir/common/src/squidprotocol/squidProtocolFormatter.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DataNode.dir/build.make CMakeFiles/DataNode.dir/common/src/squidprotocol/squidProtocolFormatter.cpp.o
.PHONY : common/src/squidprotocol/squidProtocolFormatter.cpp.o

common/src/squidprotocol/squidProtocolFormatter.i: common/src/squidprotocol/squidProtocolFormatter.cpp.i
.PHONY : common/src/squidprotocol/squidProtocolFormatter.i

# target to preprocess a source file
common/src/squidprotocol/squidProtocolFormatter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/common/src/squidprotocol/squidProtocolFormatter.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorageServer.dir/build.make CMakeFiles/SquidStorageServer.dir/common/src/squidprotocol/squidProtocolFormatter.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DataNode.dir/build.make CMakeFiles/DataNode.dir/common/src/squidprotocol/squidProtocolFormatter.cpp.i
.PHONY : common/src/squidprotocol/squidProtocolFormatter.cpp.i

common/src/squidprotocol/squidProtocolFormatter.s: common/src/squidprotocol/squidProtocolFormatter.cpp.s
.PHONY : common/src/squidprotocol/squidProtocolFormatter.s

# target to generate assembly for a file
common/src/squidprotocol/squidProtocolFormatter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/common/src/squidprotocol/squidProtocolFormatter.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorageServer.dir/build.make CMakeFiles/SquidStorageServer.dir/common/src/squidprotocol/squidProtocolFormatter.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DataNode.dir/build.make CMakeFiles/DataNode.dir/common/src/squidprotocol/squidProtocolFormatter.cpp.s
.PHONY : common/src/squidprotocol/squidProtocolFormatter.cpp.s

common/src/squidprotocol/squidprotocol.o: common/src/squidprotocol/squidprotocol.cpp.o
.PHONY : common/src/squidprotocol/squidprotocol.o

# target to build an object file
common/src/squidprotocol/squidprotocol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/common/src/squidprotocol/squidprotocol.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorageServer.dir/build.make CMakeFiles/SquidStorageServer.dir/common/src/squidprotocol/squidprotocol.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DataNode.dir/build.make CMakeFiles/DataNode.dir/common/src/squidprotocol/squidprotocol.cpp.o
.PHONY : common/src/squidprotocol/squidprotocol.cpp.o

common/src/squidprotocol/squidprotocol.i: common/src/squidprotocol/squidprotocol.cpp.i
.PHONY : common/src/squidprotocol/squidprotocol.i

# target to preprocess a source file
common/src/squidprotocol/squidprotocol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/common/src/squidprotocol/squidprotocol.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorageServer.dir/build.make CMakeFiles/SquidStorageServer.dir/common/src/squidprotocol/squidprotocol.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DataNode.dir/build.make CMakeFiles/DataNode.dir/common/src/squidprotocol/squidprotocol.cpp.i
.PHONY : common/src/squidprotocol/squidprotocol.cpp.i

common/src/squidprotocol/squidprotocol.s: common/src/squidprotocol/squidprotocol.cpp.s
.PHONY : common/src/squidprotocol/squidprotocol.s

# target to generate assembly for a file
common/src/squidprotocol/squidprotocol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/common/src/squidprotocol/squidprotocol.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorageServer.dir/build.make CMakeFiles/SquidStorageServer.dir/common/src/squidprotocol/squidprotocol.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DataNode.dir/build.make CMakeFiles/DataNode.dir/common/src/squidprotocol/squidprotocol.cpp.s
.PHONY : common/src/squidprotocol/squidprotocol.cpp.s

data-node/src/datanode.o: data-node/src/datanode.cpp.o
.PHONY : data-node/src/datanode.o

# target to build an object file
data-node/src/datanode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DataNode.dir/build.make CMakeFiles/DataNode.dir/data-node/src/datanode.cpp.o
.PHONY : data-node/src/datanode.cpp.o

data-node/src/datanode.i: data-node/src/datanode.cpp.i
.PHONY : data-node/src/datanode.i

# target to preprocess a source file
data-node/src/datanode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DataNode.dir/build.make CMakeFiles/DataNode.dir/data-node/src/datanode.cpp.i
.PHONY : data-node/src/datanode.cpp.i

data-node/src/datanode.s: data-node/src/datanode.cpp.s
.PHONY : data-node/src/datanode.s

# target to generate assembly for a file
data-node/src/datanode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DataNode.dir/build.make CMakeFiles/DataNode.dir/data-node/src/datanode.cpp.s
.PHONY : data-node/src/datanode.cpp.s

data-node/src/main.o: data-node/src/main.cpp.o
.PHONY : data-node/src/main.o

# target to build an object file
data-node/src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DataNode.dir/build.make CMakeFiles/DataNode.dir/data-node/src/main.cpp.o
.PHONY : data-node/src/main.cpp.o

data-node/src/main.i: data-node/src/main.cpp.i
.PHONY : data-node/src/main.i

# target to preprocess a source file
data-node/src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DataNode.dir/build.make CMakeFiles/DataNode.dir/data-node/src/main.cpp.i
.PHONY : data-node/src/main.cpp.i

data-node/src/main.s: data-node/src/main.cpp.s
.PHONY : data-node/src/main.s

# target to generate assembly for a file
data-node/src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DataNode.dir/build.make CMakeFiles/DataNode.dir/data-node/src/main.cpp.s
.PHONY : data-node/src/main.cpp.s

imgui/backends/imgui_impl_opengl2.o: imgui/backends/imgui_impl_opengl2.cpp.o
.PHONY : imgui/backends/imgui_impl_opengl2.o

# target to build an object file
imgui/backends/imgui_impl_opengl2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/imgui/backends/imgui_impl_opengl2.cpp.o
.PHONY : imgui/backends/imgui_impl_opengl2.cpp.o

imgui/backends/imgui_impl_opengl2.i: imgui/backends/imgui_impl_opengl2.cpp.i
.PHONY : imgui/backends/imgui_impl_opengl2.i

# target to preprocess a source file
imgui/backends/imgui_impl_opengl2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/imgui/backends/imgui_impl_opengl2.cpp.i
.PHONY : imgui/backends/imgui_impl_opengl2.cpp.i

imgui/backends/imgui_impl_opengl2.s: imgui/backends/imgui_impl_opengl2.cpp.s
.PHONY : imgui/backends/imgui_impl_opengl2.s

# target to generate assembly for a file
imgui/backends/imgui_impl_opengl2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/imgui/backends/imgui_impl_opengl2.cpp.s
.PHONY : imgui/backends/imgui_impl_opengl2.cpp.s

imgui/backends/imgui_impl_sdl2.o: imgui/backends/imgui_impl_sdl2.cpp.o
.PHONY : imgui/backends/imgui_impl_sdl2.o

# target to build an object file
imgui/backends/imgui_impl_sdl2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/imgui/backends/imgui_impl_sdl2.cpp.o
.PHONY : imgui/backends/imgui_impl_sdl2.cpp.o

imgui/backends/imgui_impl_sdl2.i: imgui/backends/imgui_impl_sdl2.cpp.i
.PHONY : imgui/backends/imgui_impl_sdl2.i

# target to preprocess a source file
imgui/backends/imgui_impl_sdl2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/imgui/backends/imgui_impl_sdl2.cpp.i
.PHONY : imgui/backends/imgui_impl_sdl2.cpp.i

imgui/backends/imgui_impl_sdl2.s: imgui/backends/imgui_impl_sdl2.cpp.s
.PHONY : imgui/backends/imgui_impl_sdl2.s

# target to generate assembly for a file
imgui/backends/imgui_impl_sdl2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/imgui/backends/imgui_impl_sdl2.cpp.s
.PHONY : imgui/backends/imgui_impl_sdl2.cpp.s

imgui/imgui.o: imgui/imgui.cpp.o
.PHONY : imgui/imgui.o

# target to build an object file
imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/imgui/imgui.cpp.o
.PHONY : imgui/imgui.cpp.o

imgui/imgui.i: imgui/imgui.cpp.i
.PHONY : imgui/imgui.i

# target to preprocess a source file
imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/imgui/imgui.cpp.i
.PHONY : imgui/imgui.cpp.i

imgui/imgui.s: imgui/imgui.cpp.s
.PHONY : imgui/imgui.s

# target to generate assembly for a file
imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/imgui/imgui.cpp.s
.PHONY : imgui/imgui.cpp.s

imgui/imgui_demo.o: imgui/imgui_demo.cpp.o
.PHONY : imgui/imgui_demo.o

# target to build an object file
imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/imgui/imgui_demo.cpp.o
.PHONY : imgui/imgui_demo.cpp.o

imgui/imgui_demo.i: imgui/imgui_demo.cpp.i
.PHONY : imgui/imgui_demo.i

# target to preprocess a source file
imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/imgui/imgui_demo.cpp.i
.PHONY : imgui/imgui_demo.cpp.i

imgui/imgui_demo.s: imgui/imgui_demo.cpp.s
.PHONY : imgui/imgui_demo.s

# target to generate assembly for a file
imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/imgui/imgui_demo.cpp.s
.PHONY : imgui/imgui_demo.cpp.s

imgui/imgui_draw.o: imgui/imgui_draw.cpp.o
.PHONY : imgui/imgui_draw.o

# target to build an object file
imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/imgui/imgui_draw.cpp.o
.PHONY : imgui/imgui_draw.cpp.o

imgui/imgui_draw.i: imgui/imgui_draw.cpp.i
.PHONY : imgui/imgui_draw.i

# target to preprocess a source file
imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/imgui/imgui_draw.cpp.i
.PHONY : imgui/imgui_draw.cpp.i

imgui/imgui_draw.s: imgui/imgui_draw.cpp.s
.PHONY : imgui/imgui_draw.s

# target to generate assembly for a file
imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/imgui/imgui_draw.cpp.s
.PHONY : imgui/imgui_draw.cpp.s

imgui/imgui_tables.o: imgui/imgui_tables.cpp.o
.PHONY : imgui/imgui_tables.o

# target to build an object file
imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/imgui/imgui_tables.cpp.o
.PHONY : imgui/imgui_tables.cpp.o

imgui/imgui_tables.i: imgui/imgui_tables.cpp.i
.PHONY : imgui/imgui_tables.i

# target to preprocess a source file
imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/imgui/imgui_tables.cpp.i
.PHONY : imgui/imgui_tables.cpp.i

imgui/imgui_tables.s: imgui/imgui_tables.cpp.s
.PHONY : imgui/imgui_tables.s

# target to generate assembly for a file
imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/imgui/imgui_tables.cpp.s
.PHONY : imgui/imgui_tables.cpp.s

imgui/imgui_widgets.o: imgui/imgui_widgets.cpp.o
.PHONY : imgui/imgui_widgets.o

# target to build an object file
imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/imgui/imgui_widgets.cpp.o
.PHONY : imgui/imgui_widgets.cpp.o

imgui/imgui_widgets.i: imgui/imgui_widgets.cpp.i
.PHONY : imgui/imgui_widgets.i

# target to preprocess a source file
imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/imgui/imgui_widgets.cpp.i
.PHONY : imgui/imgui_widgets.cpp.i

imgui/imgui_widgets.s: imgui/imgui_widgets.cpp.s
.PHONY : imgui/imgui_widgets.s

# target to generate assembly for a file
imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/imgui/imgui_widgets.cpp.s
.PHONY : imgui/imgui_widgets.cpp.s

imgui/src/Application.o: imgui/src/Application.cpp.o
.PHONY : imgui/src/Application.o

# target to build an object file
imgui/src/Application.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/imgui/src/Application.cpp.o
.PHONY : imgui/src/Application.cpp.o

imgui/src/Application.i: imgui/src/Application.cpp.i
.PHONY : imgui/src/Application.i

# target to preprocess a source file
imgui/src/Application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/imgui/src/Application.cpp.i
.PHONY : imgui/src/Application.cpp.i

imgui/src/Application.s: imgui/src/Application.cpp.s
.PHONY : imgui/src/Application.s

# target to generate assembly for a file
imgui/src/Application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/imgui/src/Application.cpp.s
.PHONY : imgui/src/Application.cpp.s

imgui/src/main.o: imgui/src/main.cpp.o
.PHONY : imgui/src/main.o

# target to build an object file
imgui/src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/imgui/src/main.cpp.o
.PHONY : imgui/src/main.cpp.o

imgui/src/main.i: imgui/src/main.cpp.i
.PHONY : imgui/src/main.i

# target to preprocess a source file
imgui/src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/imgui/src/main.cpp.i
.PHONY : imgui/src/main.cpp.i

imgui/src/main.s: imgui/src/main.cpp.s
.PHONY : imgui/src/main.s

# target to generate assembly for a file
imgui/src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorage.dir/build.make CMakeFiles/SquidStorage.dir/imgui/src/main.cpp.s
.PHONY : imgui/src/main.cpp.s

server/src/main.o: server/src/main.cpp.o
.PHONY : server/src/main.o

# target to build an object file
server/src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorageServer.dir/build.make CMakeFiles/SquidStorageServer.dir/server/src/main.cpp.o
.PHONY : server/src/main.cpp.o

server/src/main.i: server/src/main.cpp.i
.PHONY : server/src/main.i

# target to preprocess a source file
server/src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorageServer.dir/build.make CMakeFiles/SquidStorageServer.dir/server/src/main.cpp.i
.PHONY : server/src/main.cpp.i

server/src/main.s: server/src/main.cpp.s
.PHONY : server/src/main.s

# target to generate assembly for a file
server/src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorageServer.dir/build.make CMakeFiles/SquidStorageServer.dir/server/src/main.cpp.s
.PHONY : server/src/main.cpp.s

server/src/server.o: server/src/server.cpp.o
.PHONY : server/src/server.o

# target to build an object file
server/src/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorageServer.dir/build.make CMakeFiles/SquidStorageServer.dir/server/src/server.cpp.o
.PHONY : server/src/server.cpp.o

server/src/server.i: server/src/server.cpp.i
.PHONY : server/src/server.i

# target to preprocess a source file
server/src/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorageServer.dir/build.make CMakeFiles/SquidStorageServer.dir/server/src/server.cpp.i
.PHONY : server/src/server.cpp.i

server/src/server.s: server/src/server.cpp.s
.PHONY : server/src/server.s

# target to generate assembly for a file
server/src/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SquidStorageServer.dir/build.make CMakeFiles/SquidStorageServer.dir/server/src/server.cpp.s
.PHONY : server/src/server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... DataNode"
	@echo "... SquidStorage"
	@echo "... SquidStorageServer"
	@echo "... client/src/client.o"
	@echo "... client/src/client.i"
	@echo "... client/src/client.s"
	@echo "... common/src/filesystem/filelock.o"
	@echo "... common/src/filesystem/filelock.i"
	@echo "... common/src/filesystem/filelock.s"
	@echo "... common/src/filesystem/filemanager.o"
	@echo "... common/src/filesystem/filemanager.i"
	@echo "... common/src/filesystem/filemanager.s"
	@echo "... common/src/filesystem/filetransfer.o"
	@echo "... common/src/filesystem/filetransfer.i"
	@echo "... common/src/filesystem/filetransfer.s"
	@echo "... common/src/peer/peer.o"
	@echo "... common/src/peer/peer.i"
	@echo "... common/src/peer/peer.s"
	@echo "... common/src/squidprotocol/squidProtocolFormatter.o"
	@echo "... common/src/squidprotocol/squidProtocolFormatter.i"
	@echo "... common/src/squidprotocol/squidProtocolFormatter.s"
	@echo "... common/src/squidprotocol/squidprotocol.o"
	@echo "... common/src/squidprotocol/squidprotocol.i"
	@echo "... common/src/squidprotocol/squidprotocol.s"
	@echo "... data-node/src/datanode.o"
	@echo "... data-node/src/datanode.i"
	@echo "... data-node/src/datanode.s"
	@echo "... data-node/src/main.o"
	@echo "... data-node/src/main.i"
	@echo "... data-node/src/main.s"
	@echo "... imgui/backends/imgui_impl_opengl2.o"
	@echo "... imgui/backends/imgui_impl_opengl2.i"
	@echo "... imgui/backends/imgui_impl_opengl2.s"
	@echo "... imgui/backends/imgui_impl_sdl2.o"
	@echo "... imgui/backends/imgui_impl_sdl2.i"
	@echo "... imgui/backends/imgui_impl_sdl2.s"
	@echo "... imgui/imgui.o"
	@echo "... imgui/imgui.i"
	@echo "... imgui/imgui.s"
	@echo "... imgui/imgui_demo.o"
	@echo "... imgui/imgui_demo.i"
	@echo "... imgui/imgui_demo.s"
	@echo "... imgui/imgui_draw.o"
	@echo "... imgui/imgui_draw.i"
	@echo "... imgui/imgui_draw.s"
	@echo "... imgui/imgui_tables.o"
	@echo "... imgui/imgui_tables.i"
	@echo "... imgui/imgui_tables.s"
	@echo "... imgui/imgui_widgets.o"
	@echo "... imgui/imgui_widgets.i"
	@echo "... imgui/imgui_widgets.s"
	@echo "... imgui/src/Application.o"
	@echo "... imgui/src/Application.i"
	@echo "... imgui/src/Application.s"
	@echo "... imgui/src/main.o"
	@echo "... imgui/src/main.i"
	@echo "... imgui/src/main.s"
	@echo "... server/src/main.o"
	@echo "... server/src/main.i"
	@echo "... server/src/main.s"
	@echo "... server/src/server.o"
	@echo "... server/src/server.i"
	@echo "... server/src/server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

