name: CMake Build (Ubuntu + macOS)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B build

    - name: Build
      run: cmake --build build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-app-${{ matrix.os }}
        path: |
          build/my-executable  # <-- cambia questo con il tuo eseguibile
