name: CMake Build (Ubuntu + macOS)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (SDL2 + GLEW)
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y libsdl2-dev libglew-dev
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew update
            brew install sdl2 sdl2_image sdl2_mixer sdl2_ttf glew glfw
          fi
        shell: bash

      - name: Configure CMake
        run: cmake -B build

      - name: Build
        run: cmake --build build
        continue-on-error: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SquidStorage-${{ matrix.os }}
          path: |
            build/SquidStorage

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SquidStorageServer-${{ matrix.os }}
          path: |
            build/SquidStorageServer

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DataNode-${{ matrix.os }}
          path: |
            build/DataNode

  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    # needs: test
    if: github.event_name == 'push'
    outputs:
      released:       ${{ steps.semrel.outputs.new_release_published }}
      version:        ${{ steps.semrel.outputs.new_release_version }}
      version_major:  ${{ steps.semrel.outputs.new_release_major_version }}
      version_minor:  ${{ steps.semrel.outputs.new_release_minor_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run semantic-release
        id: semrel
        uses: cycjimmy/semantic-release-action@v6
        with:
          extra_plugins: |
            @semantic-release/github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
